# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 925fa0177bc178f15127ffeb371c293aebd50287eedfbdfefceed4d67dbad1e108a1775d8aa9688498cc0437a0629c30b9bfbe38869c76b9ce25f429cc0a5856

test:
  secret_key_base: ebe67e3718eb1214348b1597c6da3bc1f9e2b050a32d1c6e5a041edc3326e5142ceb091891bb307988b35925b976c91d18de625458e27f13fc7af5eaabeb00fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
